// Input data for the Field Shift Explorer.
// GENERATED by build_field_data.py — do not edit by hand.
// Every field below is derived entirely from its folder under ./data/:
//   data/<field>/raw_data.csv               (per-year, per-level document counts)
//   data/<field>/per_year_summaries.json    (per-year story + requirement chips)
//   data/<field>/all_year_summaries.json    (turning points -> eras, narrative)
// To change what the web shows: add/edit a folder under data/, then run
//   python3 build_field_data.py
// Counts (phd/msc/grant) and stories are real; eras, lifelines, maturity and
// tagline are derived deterministically from the same files.

export const SPAN = [2003, 2026];

export const FIELDS = {

  sentiment_analysis:
    {
        "label": "Sentiment Analysis",
        "maturity": 0.89,
        "tagline": "6 method generations across 2003–2026 — now centred on Statistical and econometric.",
        "eras": [
            {
                "name": "Foundational",
                "a": 2003,
                "b": 2006,
                "c": "#c9a14a",
                "note": "The field's run-up — before the first major shift in its method stack."
            },
            {
                "name": "Social media text",
                "a": 2006,
                "b": 2017,
                "c": "#5b8a72",
                "note": "Social media text data becomes a primary data source for the first time, but only in the context of blogosphere analysis, not yet sentiment analysis; this marks the beginning of a persistent reliance on user-generated content that expands dramatically in later years."
            },
            {
                "name": "GPU compute",
                "a": 2017,
                "b": 2021,
                "c": "#4a78c2",
                "note": "GPU compute for deep learning training becomes a consistently cited requirement, replacing earlier references to distributed computing (Hadoop, MapReduce) and large-scale data processing infrastructure, signaling a shift from big data platforms to specialized hardware for neural network training."
            },
            {
                "name": "Qualitative interviews",
                "a": 2021,
                "b": 2023,
                "c": "#8a5fb0",
                "note": "Qualitative interviews and surveys first appear as a required method for gathering subjective data, marking a shift toward mixed-methods research that combines computational analysis with human-centered data collection."
            },
            {
                "name": "LLMs",
                "a": 2023,
                "b": 2024,
                "c": "#3f8a9a",
                "note": "Large Language Models (LLMs) emerge as a distinct data and method category, moving beyond earlier mentions of pre-trained models like BERT to encompass a broader emphasis on LLMs as a foundation for AI systems, often with a focus on efficiency or adaptation."
            },
            {
                "name": "Statistical and econometric",
                "a": 2024,
                "b": 2026.2,
                "c": "#cf5b3e",
                "note": "Statistical and econometric analysis emerges as a required method for hypothesis testing and regression, complementing the existing machine learning and NLP techniques, and reflecting a growing integration of traditional social science methodology with computational analysis."
            }
        ],
        "turningPoints": [
            {
                "y": 2006,
                "t": "Social media text"
            },
            {
                "y": 2017,
                "t": "GPU compute"
            },
            {
                "y": 2021,
                "t": "Qualitative interviews"
            },
            {
                "y": 2023,
                "t": "LLMs"
            },
            {
                "y": 2024,
                "t": "Statistical and econometric"
            }
        ],
        "volume": {
            "thesis": [
                0,
                0,
                0,
                0,
                1,
                1,
                3,
                5,
                4,
                8,
                8,
                9,
                18,
                23,
                21,
                23,
                30,
                18,
                16,
                24,
                25,
                26,
                22,
                0
            ],
            "grant": [
                3,
                0,
                0,
                2,
                6,
                6,
                10,
                9,
                4,
                20,
                17,
                29,
                22,
                31,
                19,
                27,
                41,
                31,
                31,
                36,
                28,
                30,
                32,
                3
            ]
        },
        "phd": [
            0,
            0,
            0,
            0,
            1,
            0,
            1,
            3,
            0,
            3,
            2,
            2,
            8,
            9,
            14,
            8,
            12,
            8,
            7,
            4,
            4,
            6,
            8,
            0
        ],
        "msc": [
            0,
            0,
            0,
            0,
            0,
            1,
            2,
            2,
            4,
            5,
            6,
            7,
            10,
            14,
            7,
            15,
            18,
            10,
            9,
            20,
            21,
            20,
            14,
            0
        ],
        "lifelines": {
            "methods": [
                {
                    "label": "Machine learning",
                    "s": 2008,
                    "e": 2026,
                    "color": "#4f7a6b",
                    "op": 0.85
                },
                {
                    "label": "Sentiment analysis",
                    "s": 2010,
                    "e": 2026,
                    "color": "#3f6ea5",
                    "op": 0.85
                },
                {
                    "label": "Natural language processing",
                    "s": 2010,
                    "e": 2026,
                    "color": "#7a5aa0",
                    "op": 0.85
                },
                {
                    "label": "Topic modeling",
                    "s": 2018,
                    "e": 2026,
                    "color": "#b8553a",
                    "op": 0.85
                },
                {
                    "label": "Deep Learning",
                    "s": 2019,
                    "e": 2021,
                    "color": "#b08a3e",
                    "op": 0.85
                },
                {
                    "label": "Large Language Models / trans…",
                    "s": 2024,
                    "e": 2026,
                    "color": "#9aa0a6",
                    "op": 0.85
                }
            ],
            "data": [
                {
                    "label": "Subjectivity and sentiment le…",
                    "s": 2008,
                    "e": 2009,
                    "color": "#5a8a7a",
                    "op": 0.85
                },
                {
                    "label": "Online text corpora",
                    "s": 2009,
                    "e": 2011,
                    "color": "#3f9a84",
                    "op": 0.85
                },
                {
                    "label": "Social Media Data",
                    "s": 2012,
                    "e": 2026,
                    "color": "#3f8a9a",
                    "op": 0.85
                },
                {
                    "label": "Large-scale text corpora from…",
                    "s": 2012,
                    "e": 2016,
                    "color": "#5f9aa8",
                    "op": 0.85
                },
                {
                    "label": "User-generated Content and Re…",
                    "s": 2014,
                    "e": 2023,
                    "color": "#7aa0b0",
                    "op": 0.85
                }
            ],
            "compute": [
                {
                    "label": "Large-scale data processing i…",
                    "s": 2006,
                    "e": 2015,
                    "color": "#c7a14a",
                    "op": 0.85
                },
                {
                    "label": "High-performance computing in…",
                    "s": 2008,
                    "e": 2012,
                    "color": "#b8862f",
                    "op": 0.85
                },
                {
                    "label": "GPU compute for deep learning",
                    "s": 2017,
                    "e": 2026,
                    "color": "#cf8a3e",
                    "op": 0.85
                }
            ]
        },
        "constants": [],
        "years": {
            "2003": "Research in 2003 spans social science and computational linguistics. One thesis examines European integration's impact on nationalist movements in Spain using protest event data from newspapers and statistical analysis. Another thesis develops graph-based algorithms for text processing tasks such as sentiment categorization and document retrieval. Both projects rely on quantitative data analysis but in different domains.",
            "2006": "The single thesis from 2006 focuses on developing algorithms and software tools to discover coalitions and identify leaders in the blogosphere. It aims to track the formation and evolution of social groups within the large and dynamic online communication space. The research highlights the challenge of analyzing massive amounts of data and the difficulty of characterizing nuanced opinions. This work is part of an early effort to computationally analyze social networks in the blogosphere.",
            "2007": "In 2007, theses spanned diverse fields including political science, literature, cultural studies, and computational linguistics. Research in law and social science examined historical attacks on the federal judiciary using large-N datasets and case studies. Humanities projects explored representations of slavery and African-American women's sexuality through archival sources, close reading, and ethnographic methods. A business-oriented project developed software to aggregate internet chatter and correlate it with sales metrics using statistical analysis. Computational linguistic research applied sentiment analysis to Chinese and English media texts. Overall, the year relied heavily on archival and textual data, qualitative methods, and the nascent application of statistical and NLP tools.",
            "2008": "In 2008, research focused on sentiment and subjectivity analysis, opinion retrieval, and financial data mining. Theses explored word sense disambiguation for subjectivity, handling negation and temporal aspects in opinion retrieval, and building scalable systems for financial market analysis. They relied on manually or automatically constructed lexicons, parallel algorithms for correlation and clustering, and machine learning techniques for community and sentiment mining. The work aimed to improve search engine technology, risk management, and personalized media recommendations.",
            "2009": "Research in 2009 was heavily focused on sentiment and subjectivity analysis, with multiple theses aiming to extract opinions from informal online sources like blogs and news. Work drew on natural language processing techniques including machine learning, statistical analysis, and symbolic parsing, and relied on manually or automatically constructed lexicons. A recurring theme was the need to handle ambiguity and compositional meaning beyond simple word-level polarity counting. Several projects also pursued cross-domain knowledge transfer using matrix decompositions and aimed to commercialize trend analysis tools by scaling to large text corpora via cloud computing. Multilingual subjectivity analysis and word-sense disambiguation emerged as important challenges.",
            "2010": "The 2010 theses covered a diverse range of research, from historical archival analysis of Newfoundland's Commission government to computational sentiment analysis of news articles and financial analyst reports. Several projects focused on developing and applying machine learning and natural language processing techniques for opinion mining and trend detection, often leveraging large-scale text corpora from news, blogs, or social media. Social science research examined public attitudes toward Latinos using survey data linked to county-level demographic and economic statistics. The research landscape was characterized by a mix of traditional archival and survey-based methods alongside emerging computational approaches to extract insights from unstructured text.",
            "2011": "Research in 2011 focused heavily on sentiment analysis and opinion mining in online content, particularly for tourism and knowledge worker applications. Theses employed mixed methods, combining semantic analysis, structural equation modeling, and qualitative frameworks. Studies drew on social psychology, media effects, and linguistic theory, and required significant human effort for manual coding, survey design, and testing. The work also relied on software tools for semantic role labeling, text classification, and aggregation, as well as compute for statistical modeling and content processing.",
            "2012": "In 2012, research heavily focused on sentiment analysis, opinion mining, and the intersection of social network analysis with natural language processing. Many projects aimed to leverage existing lexical resources (WordNet, FrameNet, PropBank, VerbNet) and large-scale text corpora, often from social media, to perform deeper semantic understanding and coreference resolution. There was a strong emphasis on developing unsupervised or weakly-supervised methods to reduce reliance on expensive hand-annotated data, while several projects required substantial computational infrastructure for processing large datasets. The year also saw work on multilingual and cross-domain challenges, particularly in sentiment analysis and named entity recognition, as well as attempts to formalize and visualize online political polarization and opinion influence.",
            "2013": "In 2013, theses heavily focused on sentiment analysis and opinion mining across diverse text types, particularly from social media (Twitter, Facebook) and web sources (news, blogs, Google data). Many projects aimed at developing multilingual and cross-media platforms capable of integrating sentiment with spatiotemporal and network analysis. Researchers commonly depended on large-scale text corpora, machine learning algorithms, and custom NLP tools, often requiring significant computational resources for data processing. There was also notable interest in leveraging Google Trends and search data for applications ranging from brand valuation to tracking hate speech and financial contagion. Additionally, linguistic annotation infrastructure and text classification methods were advanced to support these analyses.",
            "2014": "In 2014, the research landscape is dominated by the analysis of large volumes of unstructured text data, particularly from social media and web sources, to extract sentiment, opinions, and public reactions. Many projects focus on developing and applying natural language processing (NLP) and machine learning techniques for tasks like sentiment analysis, text summarization, and topic modeling, often requiring scalable computational frameworks. A recurring theme is the use of social media data (e.g., Twitter) to study public reactions to events, consumer behavior, and cultural engagement, with significant investment in building automated analysis tools and prototypes. The research draws heavily on existing social media platforms, NLP methods, and distributed computing systems like Hadoop and MapReduce.",
            "2015": "In 2015, research strongly focused on developing and applying sentiment analysis, opinion mining, and predictive analytics across diverse domains such as finance, social media, health, supply chains, and media. Many theses involved building large-scale systems that integrate and process unstructured data from multiple sources, including news articles, social media streams, and corporate disclosures. Common methodological dependencies included natural language processing (NLP), machine learning, deep learning, text summarization, and graph theory. A significant number of projects required substantial computational resources for big data processing and model training, as well as human effort for annotation, evaluation, and domain expertise. The year also saw a notable emphasis on multilingual and cross-lingual capabilities, with several projects translating and analyzing content in languages beyond English.",
            "2016": "In 2016, research theses heavily focused on extracting and analyzing opinions, sentiments, and argumentation from text and social media, often to understand public attitudes, political dynamics, or consumer behavior. Many projects leveraged large-scale, often multilingual, datasets from online sources, social networks, or news archives, and applied methods like sentiment analysis, text mining, topic modeling, and deep learning to uncover patterns. There was a strong emphasis on handling unstructured data, integrating qualitative and quantitative approaches, and developing tools for real-time or scalable analysis, with dependencies on automated NLP techniques and machine learning for classification and prediction.",
            "2017": "In 2017, research heavily focused on sentiment analysis applied to social media and financial text, often aiming to predict market movements or public opinion. Many theses combined natural language processing (NLP), social network analysis, and machine learning to process unstructured data from platforms like Twitter. A strong emphasis was placed on developing models that are robust to variations in time, geography, and demographics, and on creating resources for under-resourced languages. Several projects also explored the use of knowledge graphs, agent-based modeling, and complex event processing for real-time analysis and risk assessment. The work frequently required large-scale text corpora, annotation efforts, and computational resources for training deep learning models.",
            "2018": "In 2018, research heavily focused on natural language processing (NLP) and sentiment analysis applied to social media and healthcare data. Many studies aimed to model, forecast, or detect patterns in human behavior, such as political polarization, financial market movements, and patient experience. There was a strong emphasis on developing and adapting machine learning methods, particularly deep neural networks and probabilistic topic models like Latent Dirichlet Allocation (LDA). The research frequently depended on large-scale text data from platforms like Twitter and online forums, requiring substantial computational resources for training complex models.",
            "2019": "In 2019, research heavily focused on applying natural language processing (NLP) and machine learning (ML) techniques, particularly sentiment analysis, topic modeling, and deep learning, to analyze text and social media data across diverse domains. Common applications included understanding public discourse on economic reforms, migration, and politics; detecting cyberbullying, hate speech, and disinformation; and predicting financial risk, consumer behavior, and human mobility. Many projects depended on large-scale, unstructured data sources such as news articles, social media posts, and corporate communications, often requiring cross-lingual capabilities and advanced computational methods like sequence models and word embeddings. A significant number of theses also addressed the societal and ethical implications of these technologies, particularly around fairness, bias, and the impact on vulnerable groups.",
            "2020": "In 2020, research heavily focused on applying Natural Language Processing (NLP) and sentiment analysis to social media and textual data for understanding public discourse, bias, customer satisfaction, and migration attitudes. Many projects also explored AI-driven solutions for healthcare, legal systems, and urban management, often leveraging deep learning and cloud technologies. A recurring theme was the use of computational methods to analyze and predict human behavior, with several theses addressing the impacts of the COVID-19 pandemic. The research landscape was characterized by interdisciplinary approaches combining computational linguistics with social sciences, and a strong emphasis on developing practical tools for industry and policy-making.",
            "2021": "In 2021, research heavily applied natural language processing (NLP) and sentiment analysis across domains such as finance, mental health, social media, and news media. Many theses leveraged large-scale user-generated data from platforms like Twitter, TikTok, and counseling chats to analyze behavior, predict outcomes, or detect bias. A significant subset focused on adversarial robustness and bias mitigation in AI systems, while others integrated machine learning with domain expertise (e.g., clinical psychology, geology, classroom observation). Common methodological dependencies include deep learning, topic modeling, named entity recognition, and computer vision, often requiring substantial compute resources for model training.",
            "2022": "In 2022, research heavily centered on sentiment analysis and natural language processing applied to diverse domains such as social media, mental health, finance, governance, and education. Many theses employed machine learning models ranging from traditional classifiers to deep learning architectures like LSTMs and Transformers, often requiring labeled datasets and computational resources for training. A significant focus was on cross-cultural and multilingual applications, including Portuguese, Norwegian, Arabic, and Chinese contexts. Other recurring themes included misinformation detection, affect recognition, and the integration of AI into workplace and clinical tools. Several projects also relied on human annotation, validation by domain experts, and mixed-method approaches combining computational analysis with qualitative interviews.",
            "2023": "In 2023, the research landscape is heavily focused on applying natural language processing (NLP) and machine learning to analyze large-scale text and social media data, particularly for sentiment analysis, emotion detection, and understanding public opinion. A significant number of theses rely on social media platforms (e.g., Twitter, Instagram, TikTok) as a primary data source, using methods like topic modeling, sentiment analysis, and network analysis. There is also a strong emphasis on developing computationally efficient methods that require reduced supervision, moving away from resource-intensive large language models. Many projects aim to make these analytical tools more accessible and applicable to specific domains, including engineering education, healthcare, finance, and cultural heritage. A recurring theme is the use of these techniques to capture and analyze the experiences of specific communities, such as neurodivergent individuals or patients, to inform better practices and policies.",
            "2024": "The 2024 theses reveal a strong focus on applying natural language processing (NLP) and sentiment analysis across diverse domains including finance, politics, social media, and health. Many projects leverage AI and machine learning to detect emotions, opinions, and disinformation, often from online text and voice data. There is a notable emphasis on making these technologies personalized, explainable, and efficient for broader accessibility. Several studies also integrate computational methods with traditional social science approaches, such as interviews and surveys, to analyze societal issues like migration, inequality, and democratic backsliding.",
            "2025": "In 2025, research heavily focused on applying AI and natural language processing (NLP) to analyze public opinion, sentiment, and discourse across domains like politics, finance, health, and tourism. Many projects used large language models (LLMs) and BERT-based models for sentiment analysis, topic modeling, and text classification, often combined with social media or user-generated content. A recurring theme was the integration of AI with traditional social science methods (surveys, interviews, experiments) to study complex socio-technical systems, including bot influence, political discontent, and trust in institutions. Several theses also developed or applied novel econometric and statistical methods for handling AI-generated data, functional time series, and multi-perspective reasoning. Overall, the year was characterized by a strong emphasis on computational social science, with researchers leveraging advanced machine learning and large-scale text data to address societal challenges.",
            "2026": "In 2026, research focused on applying advanced NLP, particularly large language models, to historical discourse analysis within an interdisciplinary framework combining computer science, history, economics, and management. One thesis leveraged LLMs and digitized press archives from Gallica to study narratives about corporate profit from 1907 to 1950, employing methods such as sentiment analysis, multimodal content analysis, and diachronic network mapping. It also integrated corporate accounting data from Equipex DFIH and annual reports to link discourse with firm-level behavior. Another major activity was the organization of the NLDB 2026 conference, which gathered researchers to discuss topics like large language models, bias, and transparency, though this is not a research project itself. Overall, the year’s research landscape is defined by the use of historical datasets and computationally intensive NLP methods to address societal questions."
        },
        "yearReqs": {
            "2003": [
                {
                    "name": "Spanish political protest and economic integration data",
                    "group": "Data"
                },
                {
                    "name": "Text corpora for sentiment and document retrieval",
                    "group": "Data"
                },
                {
                    "name": "Graph-based algorithms for text processing",
                    "group": "Methods"
                },
                {
                    "name": "Statistical regression analysis",
                    "group": "Methods"
                }
            ],
            "2006": [
                {
                    "name": "Blogosphere data",
                    "group": "Data"
                },
                {
                    "name": "Coalition discovery algorithms",
                    "group": "Methods"
                },
                {
                    "name": "Large-scale data processing compute",
                    "group": "Compute"
                }
            ],
            "2007": [
                {
                    "name": "Archival and textual primary sources",
                    "group": "Data"
                },
                {
                    "name": "Internet and media text data",
                    "group": "Data"
                },
                {
                    "name": "Qualitative research methods",
                    "group": "Methods"
                },
                {
                    "name": "Statistical and computational analysis",
                    "group": "Methods"
                },
                {
                    "name": "Web scraping and NLP tools",
                    "group": "Tools"
                },
                {
                    "name": "Data processing computational resources",
                    "group": "Compute"
                }
            ],
            "2008": [
                {
                    "name": "Subjectivity and sentiment lexicons",
                    "group": "Data"
                },
                {
                    "name": "Financial market data",
                    "group": "Data"
                },
                {
                    "name": "Online media and community data",
                    "group": "Data"
                },
                {
                    "name": "Word sense disambiguation for subjectivity",
                    "group": "Methods"
                },
                {
                    "name": "Negation handling in opinion retrieval",
                    "group": "Methods"
                },
                {
                    "name": "Temporal sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Parallel algorithms for correlation and clustering",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning for community and sentiment mining",
                    "group": "Methods"
                },
                {
                    "name": "High-performance computing clusters",
                    "group": "Compute"
                }
            ],
            "2009": [
                {
                    "name": "Online text corpora (blogs, news, reviews)",
                    "group": "Data"
                },
                {
                    "name": "Subjectivity and sentiment lexicons",
                    "group": "Data"
                },
                {
                    "name": "Machine learning for sentiment classification",
                    "group": "Methods"
                },
                {
                    "name": "Statistical and symbolic NLP",
                    "group": "Methods"
                },
                {
                    "name": "Cloud computing infrastructure",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation of linguistic data",
                    "group": "Human"
                }
            ],
            "2010": [
                {
                    "name": "News and blog text corpora",
                    "group": "Data"
                },
                {
                    "name": "Survey and census demographic data",
                    "group": "Data"
                },
                {
                    "name": "Historical archival records",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis / opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Natural language and statistical analysis for trend detection",
                    "group": "Methods"
                },
                {
                    "name": "Cloud computing infrastructure",
                    "group": "Compute"
                },
                {
                    "name": "Corpus analysis software",
                    "group": "Tools"
                }
            ],
            "2011": [
                {
                    "name": "Sentiment analysis and opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Mixed methods research design",
                    "group": "Methods"
                },
                {
                    "name": "Online text and social media content",
                    "group": "Data"
                },
                {
                    "name": "Semantic role labeling and text analysis tools",
                    "group": "Tools"
                },
                {
                    "name": "Manual content coding and survey administration",
                    "group": "Human"
                },
                {
                    "name": "Statistical modeling and classification compute",
                    "group": "Compute"
                }
            ],
            "2012": [
                {
                    "name": "Social media text datasets",
                    "group": "Data"
                },
                {
                    "name": "Lexical resources (WordNet, FrameNet, PropBank, VerbNet)",
                    "group": "Data"
                },
                {
                    "name": "Large-scale annotated corpora for NLP",
                    "group": "Data"
                },
                {
                    "name": "Multilingual text resources for sentiment and named entity recognition",
                    "group": "Data"
                },
                {
                    "name": "Unsupervised or weakly-supervised machine learning for grammar and semantics",
                    "group": "Methods"
                },
                {
                    "name": "Sentiment analysis and opinion influence modeling",
                    "group": "Methods"
                },
                {
                    "name": "High-performance computing infrastructure for large-scale text processing",
                    "group": "Compute"
                },
                {
                    "name": "Expert annotation and gold standard creation for semantic roles and frames",
                    "group": "Human"
                },
                {
                    "name": "API-based data collection and visualization tools for social media",
                    "group": "Tools"
                }
            ],
            "2013": [
                {
                    "name": "Social media and web text data",
                    "group": "Data"
                },
                {
                    "name": "Google Trends and search data",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis and opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning and natural language processing",
                    "group": "Methods"
                },
                {
                    "name": "Multilingual text analysis platforms and lexical resources",
                    "group": "Tools"
                },
                {
                    "name": "Large-scale data processing infrastructure",
                    "group": "Compute"
                }
            ],
            "2014": [
                {
                    "name": "Social media text data",
                    "group": "Data"
                },
                {
                    "name": "Natural language processing (NLP) for sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning and statistical modeling tools",
                    "group": "Tools"
                },
                {
                    "name": "Distributed computing (Hadoop and MapReduce)",
                    "group": "Compute"
                },
                {
                    "name": "User-generated content from web platforms",
                    "group": "Data"
                },
                {
                    "name": "Automated text summarization and topic modeling",
                    "group": "Methods"
                }
            ],
            "2015": [
                {
                    "name": "News articles",
                    "group": "Data"
                },
                {
                    "name": "Social media data (Twitter, Facebook, StockTwits, blogs)",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis / opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Natural language processing (NLP)",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning / deep learning",
                    "group": "Methods"
                },
                {
                    "name": "Textual analysis / sentiment lexicon tools",
                    "group": "Tools"
                },
                {
                    "name": "Large-scale data processing infrastructure",
                    "group": "Compute"
                },
                {
                    "name": "Human annotation / evaluation (crowdsourcing, expert review)",
                    "group": "Human"
                }
            ],
            "2016": [
                {
                    "name": "Large-scale text corpora from social media and news",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis and opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Natural language processing (NLP) and text mining",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning and deep learning",
                    "group": "Methods"
                },
                {
                    "name": "Statistical and econometric modeling",
                    "group": "Methods"
                },
                {
                    "name": "Visualization and data presentation tools",
                    "group": "Tools"
                }
            ],
            "2017": [
                {
                    "name": "Social media text data (Twitter, Facebook, etc.)",
                    "group": "Data"
                },
                {
                    "name": "Financial news and reports",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Natural language processing (NLP)",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning (including deep learning)",
                    "group": "Methods"
                },
                {
                    "name": "Social network analysis (SNA)",
                    "group": "Methods"
                },
                {
                    "name": "Bayesian modeling",
                    "group": "Methods"
                },
                {
                    "name": "Agent-based modeling",
                    "group": "Methods"
                },
                {
                    "name": "Pre-trained language models (e.g., BERT)",
                    "group": "Tools"
                },
                {
                    "name": "GPU compute for model training",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation of text data",
                    "group": "Human"
                }
            ],
            "2018": [
                {
                    "name": "Social media text data",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic modeling (Latent Dirichlet Allocation)",
                    "group": "Methods"
                },
                {
                    "name": "Deep neural networks",
                    "group": "Methods"
                },
                {
                    "name": "Python NLP libraries",
                    "group": "Tools"
                },
                {
                    "name": "GPU compute for deep learning",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation for sentiment and topics",
                    "group": "Human"
                }
            ],
            "2019": [
                {
                    "name": "Sentiment and Emotion Analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic Modeling",
                    "group": "Methods"
                },
                {
                    "name": "Deep Learning (including LSTM, Transformers, CNNs)",
                    "group": "Methods"
                },
                {
                    "name": "Social Media Data (Twitter, Facebook, etc.)",
                    "group": "Data"
                },
                {
                    "name": "News Article Corpora",
                    "group": "Data"
                },
                {
                    "name": "Python and NLP Libraries (e.g., NLTK, spaCy, scikit-learn)",
                    "group": "Tools"
                },
                {
                    "name": "GPU Computing for Deep Learning",
                    "group": "Compute"
                },
                {
                    "name": "Expert Annotation for Text Classification",
                    "group": "Human"
                }
            ],
            "2020": [
                {
                    "name": "Social media data (Twitter, Facebook, Reddit)",
                    "group": "Data"
                },
                {
                    "name": "Textual corpora (archival descriptions, novels, legal cases, news)",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic modeling",
                    "group": "Methods"
                },
                {
                    "name": "Deep learning (neural networks, transformers)",
                    "group": "Methods"
                },
                {
                    "name": "Natural Language Processing (NLP) libraries and APIs",
                    "group": "Tools"
                },
                {
                    "name": "GPU compute for training deep learning models",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation and labeling of text data",
                    "group": "Human"
                }
            ],
            "2021": [
                {
                    "name": "Social media text data",
                    "group": "Data"
                },
                {
                    "name": "News article corpus",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Deep learning for NLP and computer vision",
                    "group": "Methods"
                },
                {
                    "name": "GPU compute for deep learning training",
                    "group": "Compute"
                },
                {
                    "name": "Qualitative interviews and surveys",
                    "group": "Human"
                }
            ],
            "2022": [
                {
                    "name": "Sentiment Analysis",
                    "group": "Methods"
                },
                {
                    "name": "Machine Learning / Deep Learning Models",
                    "group": "Methods"
                },
                {
                    "name": "Public and Proprietary Datasets",
                    "group": "Data"
                },
                {
                    "name": "GPU / High-Performance Computing",
                    "group": "Compute"
                },
                {
                    "name": "Human Annotation / Expert Validation",
                    "group": "Human"
                },
                {
                    "name": "NLP Libraries and Frameworks",
                    "group": "Tools"
                }
            ],
            "2023": [
                {
                    "name": "Social Media Text Data",
                    "group": "Data"
                },
                {
                    "name": "Natural Language Processing (NLP) Techniques",
                    "group": "Methods"
                },
                {
                    "name": "Machine Learning for Efficiency and Reduced Supervision",
                    "group": "Methods"
                },
                {
                    "name": "Large Language Models (LLMs)",
                    "group": "Data"
                },
                {
                    "name": "User-generated Content and Reviews",
                    "group": "Data"
                }
            ],
            "2024": [
                {
                    "name": "Sentiment analysis / emotion detection",
                    "group": "Methods"
                },
                {
                    "name": "Large Language Models (LLMs) / transformer-based NLP",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning frameworks and libraries",
                    "group": "Tools"
                },
                {
                    "name": "Social media and online text data",
                    "group": "Data"
                },
                {
                    "name": "GPU compute for model training and inference",
                    "group": "Compute"
                },
                {
                    "name": "Text mining and NLP libraries (e.g., NLTK, spaCy, Gensim)",
                    "group": "Tools"
                },
                {
                    "name": "Qualitative methods (interviews, focus groups, discourse analysis)",
                    "group": "Methods"
                },
                {
                    "name": "Manual annotation / labeling of data",
                    "group": "Human"
                },
                {
                    "name": "Financial and economic datasets",
                    "group": "Data"
                },
                {
                    "name": "Statistical and econometric analysis",
                    "group": "Methods"
                }
            ],
            "2025": [
                {
                    "name": "Natural Language Processing (NLP) for sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Large Language Models (LLMs) for text generation and analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic modeling",
                    "group": "Methods"
                },
                {
                    "name": "BERT-based models (e.g., FinBERT, EconBERT)",
                    "group": "Tools"
                },
                {
                    "name": "Social media data (Twitter, Facebook, Instagram, Tripadvisor)",
                    "group": "Data"
                },
                {
                    "name": "Mixed-methods (qualitative and quantitative)",
                    "group": "Methods"
                },
                {
                    "name": "Causal inference and quasi-experimental designs",
                    "group": "Methods"
                },
                {
                    "name": "GPU compute for training deep learning models",
                    "group": "Compute"
                },
                {
                    "name": "Machine learning for prediction and trend detection",
                    "group": "Methods"
                },
                {
                    "name": "Financial and economic datasets (e.g., hedge fund letters, proxy voting records, options data)",
                    "group": "Data"
                }
            ],
            "2026": [
                {
                    "name": "Digitized historical press archives",
                    "group": "Data"
                },
                {
                    "name": "Corporate accounting and annual report data",
                    "group": "Data"
                },
                {
                    "name": "Large Language Model tailored for historical discourse",
                    "group": "Methods"
                },
                {
                    "name": "Multimodal content analysis and diachronic network mapping",
                    "group": "Methods"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "User-friendly visualization tools",
                    "group": "Tools"
                }
            ]
        }
    },

  room_temperature_superconductor:
    {
        "label": "Room Temperature Superconductor",
        "maturity": 0.88,
        "tagline": "6 method generations across 2003–2026 — now centred on Statistical and econometric.",
        "eras": [
            {
                "name": "Foundational",
                "a": 2003,
                "b": 2006,
                "c": "#c9a14a",
                "note": "The field's run-up — before the first major shift in its method stack."
            },
            {
                "name": "Social media text",
                "a": 2006,
                "b": 2017,
                "c": "#5b8a72",
                "note": "Social media text data becomes a primary data source for the first time, but only in the context of blogosphere analysis, not yet sentiment analysis; this marks the beginning of a persistent reliance on user-generated content that expands dramatically in later years."
            },
            {
                "name": "GPU compute",
                "a": 2017,
                "b": 2021,
                "c": "#4a78c2",
                "note": "GPU compute for deep learning training becomes a consistently cited requirement, replacing earlier references to distributed computing (Hadoop, MapReduce) and large-scale data processing infrastructure, signaling a shift from big data platforms to specialized hardware for neural network training."
            },
            {
                "name": "Qualitative interviews",
                "a": 2021,
                "b": 2023,
                "c": "#8a5fb0",
                "note": "Qualitative interviews and surveys first appear as a required method for gathering subjective data, marking a shift toward mixed-methods research that combines computational analysis with human-centered data collection."
            },
            {
                "name": "LLMs",
                "a": 2023,
                "b": 2024,
                "c": "#3f8a9a",
                "note": "Large Language Models (LLMs) emerge as a distinct data and method category, moving beyond earlier mentions of pre-trained models like BERT to encompass a broader emphasis on LLMs as a foundation for AI systems, often with a focus on efficiency or adaptation."
            },
            {
                "name": "Statistical and econometric",
                "a": 2024,
                "b": 2026.2,
                "c": "#cf5b3e",
                "note": "Statistical and econometric analysis emerges as a required method for hypothesis testing and regression, complementing the existing machine learning and NLP techniques, and reflecting a growing integration of traditional social science methodology with computational analysis."
            }
        ],
        "turningPoints": [
            {
                "y": 2006,
                "t": "Social media text"
            },
            {
                "y": 2017,
                "t": "GPU compute"
            },
            {
                "y": 2021,
                "t": "Qualitative interviews"
            },
            {
                "y": 2023,
                "t": "LLMs"
            },
            {
                "y": 2024,
                "t": "Statistical and econometric"
            }
        ],
        "volume": {
            "thesis": [
                1,
                2,
                2,
                0,
                0,
                3,
                3,
                4,
                7,
                1,
                3,
                7,
                3,
                4,
                9,
                8,
                4,
                4,
                7,
                14,
                8,
                8,
                6,
                1
            ],
            "grant": [
                2,
                1,
                1,
                0,
                1,
                3,
                3,
                4,
                5,
                5,
                1,
                2,
                2,
                6,
                2,
                2,
                0,
                6,
                5,
                5,
                15,
                2,
                0,
                0
            ]
        },
        "phd": [
            1,
            1,
            2,
            0,
            0,
            2,
            3,
            2,
            3,
            1,
            3,
            5,
            2,
            3,
            8,
            8,
            3,
            4,
            7,
            13,
            8,
            8,
            5,
            0
        ],
        "msc": [
            0,
            1,
            0,
            0,
            0,
            1,
            0,
            2,
            4,
            0,
            0,
            2,
            1,
            1,
            1,
            0,
            1,
            0,
            0,
            1,
            0,
            0,
            1,
            1
        ],
        "lifelines": {
            "methods": [
                {
                    "label": "Machine learning",
                    "s": 2008,
                    "e": 2026,
                    "color": "#4f7a6b",
                    "op": 0.85
                },
                {
                    "label": "Sentiment analysis",
                    "s": 2010,
                    "e": 2026,
                    "color": "#3f6ea5",
                    "op": 0.85
                },
                {
                    "label": "Natural language processing",
                    "s": 2010,
                    "e": 2026,
                    "color": "#7a5aa0",
                    "op": 0.85
                },
                {
                    "label": "Topic modeling",
                    "s": 2018,
                    "e": 2026,
                    "color": "#b8553a",
                    "op": 0.85
                },
                {
                    "label": "Deep Learning",
                    "s": 2019,
                    "e": 2021,
                    "color": "#b08a3e",
                    "op": 0.85
                },
                {
                    "label": "Large Language Models / trans…",
                    "s": 2024,
                    "e": 2026,
                    "color": "#9aa0a6",
                    "op": 0.85
                }
            ],
            "data": [
                {
                    "label": "Subjectivity and sentiment le…",
                    "s": 2008,
                    "e": 2009,
                    "color": "#5a8a7a",
                    "op": 0.85
                },
                {
                    "label": "Online text corpora",
                    "s": 2009,
                    "e": 2011,
                    "color": "#3f9a84",
                    "op": 0.85
                },
                {
                    "label": "Social Media Data",
                    "s": 2012,
                    "e": 2026,
                    "color": "#3f8a9a",
                    "op": 0.85
                },
                {
                    "label": "Large-scale text corpora from…",
                    "s": 2012,
                    "e": 2016,
                    "color": "#5f9aa8",
                    "op": 0.85
                },
                {
                    "label": "User-generated Content and Re…",
                    "s": 2014,
                    "e": 2023,
                    "color": "#7aa0b0",
                    "op": 0.85
                }
            ],
            "compute": [
                {
                    "label": "Large-scale data processing i…",
                    "s": 2006,
                    "e": 2015,
                    "color": "#c7a14a",
                    "op": 0.85
                },
                {
                    "label": "High-performance computing in…",
                    "s": 2008,
                    "e": 2012,
                    "color": "#b8862f",
                    "op": 0.85
                },
                {
                    "label": "GPU compute for deep learning",
                    "s": 2017,
                    "e": 2026,
                    "color": "#cf8a3e",
                    "op": 0.85
                }
            ]
        },
        "constants": [],
        "years": {
            "2003": "Research in 2003 spans social science and computational linguistics. One thesis examines European integration's impact on nationalist movements in Spain using protest event data from newspapers and statistical analysis. Another thesis develops graph-based algorithms for text processing tasks such as sentiment categorization and document retrieval. Both projects rely on quantitative data analysis but in different domains.",
            "2006": "The single thesis from 2006 focuses on developing algorithms and software tools to discover coalitions and identify leaders in the blogosphere. It aims to track the formation and evolution of social groups within the large and dynamic online communication space. The research highlights the challenge of analyzing massive amounts of data and the difficulty of characterizing nuanced opinions. This work is part of an early effort to computationally analyze social networks in the blogosphere.",
            "2007": "In 2007, theses spanned diverse fields including political science, literature, cultural studies, and computational linguistics. Research in law and social science examined historical attacks on the federal judiciary using large-N datasets and case studies. Humanities projects explored representations of slavery and African-American women's sexuality through archival sources, close reading, and ethnographic methods. A business-oriented project developed software to aggregate internet chatter and correlate it with sales metrics using statistical analysis. Computational linguistic research applied sentiment analysis to Chinese and English media texts. Overall, the year relied heavily on archival and textual data, qualitative methods, and the nascent application of statistical and NLP tools.",
            "2008": "In 2008, research focused on sentiment and subjectivity analysis, opinion retrieval, and financial data mining. Theses explored word sense disambiguation for subjectivity, handling negation and temporal aspects in opinion retrieval, and building scalable systems for financial market analysis. They relied on manually or automatically constructed lexicons, parallel algorithms for correlation and clustering, and machine learning techniques for community and sentiment mining. The work aimed to improve search engine technology, risk management, and personalized media recommendations.",
            "2009": "Research in 2009 was heavily focused on sentiment and subjectivity analysis, with multiple theses aiming to extract opinions from informal online sources like blogs and news. Work drew on natural language processing techniques including machine learning, statistical analysis, and symbolic parsing, and relied on manually or automatically constructed lexicons. A recurring theme was the need to handle ambiguity and compositional meaning beyond simple word-level polarity counting. Several projects also pursued cross-domain knowledge transfer using matrix decompositions and aimed to commercialize trend analysis tools by scaling to large text corpora via cloud computing. Multilingual subjectivity analysis and word-sense disambiguation emerged as important challenges.",
            "2010": "The 2010 theses covered a diverse range of research, from historical archival analysis of Newfoundland's Commission government to computational sentiment analysis of news articles and financial analyst reports. Several projects focused on developing and applying machine learning and natural language processing techniques for opinion mining and trend detection, often leveraging large-scale text corpora from news, blogs, or social media. Social science research examined public attitudes toward Latinos using survey data linked to county-level demographic and economic statistics. The research landscape was characterized by a mix of traditional archival and survey-based methods alongside emerging computational approaches to extract insights from unstructured text.",
            "2011": "Research in 2011 focused heavily on sentiment analysis and opinion mining in online content, particularly for tourism and knowledge worker applications. Theses employed mixed methods, combining semantic analysis, structural equation modeling, and qualitative frameworks. Studies drew on social psychology, media effects, and linguistic theory, and required significant human effort for manual coding, survey design, and testing. The work also relied on software tools for semantic role labeling, text classification, and aggregation, as well as compute for statistical modeling and content processing.",
            "2012": "In 2012, research heavily focused on sentiment analysis, opinion mining, and the intersection of social network analysis with natural language processing. Many projects aimed to leverage existing lexical resources (WordNet, FrameNet, PropBank, VerbNet) and large-scale text corpora, often from social media, to perform deeper semantic understanding and coreference resolution. There was a strong emphasis on developing unsupervised or weakly-supervised methods to reduce reliance on expensive hand-annotated data, while several projects required substantial computational infrastructure for processing large datasets. The year also saw work on multilingual and cross-domain challenges, particularly in sentiment analysis and named entity recognition, as well as attempts to formalize and visualize online political polarization and opinion influence.",
            "2013": "In 2013, theses heavily focused on sentiment analysis and opinion mining across diverse text types, particularly from social media (Twitter, Facebook) and web sources (news, blogs, Google data). Many projects aimed at developing multilingual and cross-media platforms capable of integrating sentiment with spatiotemporal and network analysis. Researchers commonly depended on large-scale text corpora, machine learning algorithms, and custom NLP tools, often requiring significant computational resources for data processing. There was also notable interest in leveraging Google Trends and search data for applications ranging from brand valuation to tracking hate speech and financial contagion. Additionally, linguistic annotation infrastructure and text classification methods were advanced to support these analyses.",
            "2014": "In 2014, the research landscape is dominated by the analysis of large volumes of unstructured text data, particularly from social media and web sources, to extract sentiment, opinions, and public reactions. Many projects focus on developing and applying natural language processing (NLP) and machine learning techniques for tasks like sentiment analysis, text summarization, and topic modeling, often requiring scalable computational frameworks. A recurring theme is the use of social media data (e.g., Twitter) to study public reactions to events, consumer behavior, and cultural engagement, with significant investment in building automated analysis tools and prototypes. The research draws heavily on existing social media platforms, NLP methods, and distributed computing systems like Hadoop and MapReduce.",
            "2015": "In 2015, research strongly focused on developing and applying sentiment analysis, opinion mining, and predictive analytics across diverse domains such as finance, social media, health, supply chains, and media. Many theses involved building large-scale systems that integrate and process unstructured data from multiple sources, including news articles, social media streams, and corporate disclosures. Common methodological dependencies included natural language processing (NLP), machine learning, deep learning, text summarization, and graph theory. A significant number of projects required substantial computational resources for big data processing and model training, as well as human effort for annotation, evaluation, and domain expertise. The year also saw a notable emphasis on multilingual and cross-lingual capabilities, with several projects translating and analyzing content in languages beyond English.",
            "2016": "In 2016, research theses heavily focused on extracting and analyzing opinions, sentiments, and argumentation from text and social media, often to understand public attitudes, political dynamics, or consumer behavior. Many projects leveraged large-scale, often multilingual, datasets from online sources, social networks, or news archives, and applied methods like sentiment analysis, text mining, topic modeling, and deep learning to uncover patterns. There was a strong emphasis on handling unstructured data, integrating qualitative and quantitative approaches, and developing tools for real-time or scalable analysis, with dependencies on automated NLP techniques and machine learning for classification and prediction.",
            "2017": "In 2017, research heavily focused on sentiment analysis applied to social media and financial text, often aiming to predict market movements or public opinion. Many theses combined natural language processing (NLP), social network analysis, and machine learning to process unstructured data from platforms like Twitter. A strong emphasis was placed on developing models that are robust to variations in time, geography, and demographics, and on creating resources for under-resourced languages. Several projects also explored the use of knowledge graphs, agent-based modeling, and complex event processing for real-time analysis and risk assessment. The work frequently required large-scale text corpora, annotation efforts, and computational resources for training deep learning models.",
            "2018": "In 2018, research heavily focused on natural language processing (NLP) and sentiment analysis applied to social media and healthcare data. Many studies aimed to model, forecast, or detect patterns in human behavior, such as political polarization, financial market movements, and patient experience. There was a strong emphasis on developing and adapting machine learning methods, particularly deep neural networks and probabilistic topic models like Latent Dirichlet Allocation (LDA). The research frequently depended on large-scale text data from platforms like Twitter and online forums, requiring substantial computational resources for training complex models.",
            "2019": "In 2019, research heavily focused on applying natural language processing (NLP) and machine learning (ML) techniques, particularly sentiment analysis, topic modeling, and deep learning, to analyze text and social media data across diverse domains. Common applications included understanding public discourse on economic reforms, migration, and politics; detecting cyberbullying, hate speech, and disinformation; and predicting financial risk, consumer behavior, and human mobility. Many projects depended on large-scale, unstructured data sources such as news articles, social media posts, and corporate communications, often requiring cross-lingual capabilities and advanced computational methods like sequence models and word embeddings. A significant number of theses also addressed the societal and ethical implications of these technologies, particularly around fairness, bias, and the impact on vulnerable groups.",
            "2020": "In 2020, research heavily focused on applying Natural Language Processing (NLP) and sentiment analysis to social media and textual data for understanding public discourse, bias, customer satisfaction, and migration attitudes. Many projects also explored AI-driven solutions for healthcare, legal systems, and urban management, often leveraging deep learning and cloud technologies. A recurring theme was the use of computational methods to analyze and predict human behavior, with several theses addressing the impacts of the COVID-19 pandemic. The research landscape was characterized by interdisciplinary approaches combining computational linguistics with social sciences, and a strong emphasis on developing practical tools for industry and policy-making.",
            "2021": "In 2021, research heavily applied natural language processing (NLP) and sentiment analysis across domains such as finance, mental health, social media, and news media. Many theses leveraged large-scale user-generated data from platforms like Twitter, TikTok, and counseling chats to analyze behavior, predict outcomes, or detect bias. A significant subset focused on adversarial robustness and bias mitigation in AI systems, while others integrated machine learning with domain expertise (e.g., clinical psychology, geology, classroom observation). Common methodological dependencies include deep learning, topic modeling, named entity recognition, and computer vision, often requiring substantial compute resources for model training.",
            "2022": "In 2022, research heavily centered on sentiment analysis and natural language processing applied to diverse domains such as social media, mental health, finance, governance, and education. Many theses employed machine learning models ranging from traditional classifiers to deep learning architectures like LSTMs and Transformers, often requiring labeled datasets and computational resources for training. A significant focus was on cross-cultural and multilingual applications, including Portuguese, Norwegian, Arabic, and Chinese contexts. Other recurring themes included misinformation detection, affect recognition, and the integration of AI into workplace and clinical tools. Several projects also relied on human annotation, validation by domain experts, and mixed-method approaches combining computational analysis with qualitative interviews.",
            "2023": "In 2023, the research landscape is heavily focused on applying natural language processing (NLP) and machine learning to analyze large-scale text and social media data, particularly for sentiment analysis, emotion detection, and understanding public opinion. A significant number of theses rely on social media platforms (e.g., Twitter, Instagram, TikTok) as a primary data source, using methods like topic modeling, sentiment analysis, and network analysis. There is also a strong emphasis on developing computationally efficient methods that require reduced supervision, moving away from resource-intensive large language models. Many projects aim to make these analytical tools more accessible and applicable to specific domains, including engineering education, healthcare, finance, and cultural heritage. A recurring theme is the use of these techniques to capture and analyze the experiences of specific communities, such as neurodivergent individuals or patients, to inform better practices and policies.",
            "2024": "The 2024 theses reveal a strong focus on applying natural language processing (NLP) and sentiment analysis across diverse domains including finance, politics, social media, and health. Many projects leverage AI and machine learning to detect emotions, opinions, and disinformation, often from online text and voice data. There is a notable emphasis on making these technologies personalized, explainable, and efficient for broader accessibility. Several studies also integrate computational methods with traditional social science approaches, such as interviews and surveys, to analyze societal issues like migration, inequality, and democratic backsliding.",
            "2025": "In 2025, research heavily focused on applying AI and natural language processing (NLP) to analyze public opinion, sentiment, and discourse across domains like politics, finance, health, and tourism. Many projects used large language models (LLMs) and BERT-based models for sentiment analysis, topic modeling, and text classification, often combined with social media or user-generated content. A recurring theme was the integration of AI with traditional social science methods (surveys, interviews, experiments) to study complex socio-technical systems, including bot influence, political discontent, and trust in institutions. Several theses also developed or applied novel econometric and statistical methods for handling AI-generated data, functional time series, and multi-perspective reasoning. Overall, the year was characterized by a strong emphasis on computational social science, with researchers leveraging advanced machine learning and large-scale text data to address societal challenges.",
            "2026": "In 2026, research focused on applying advanced NLP, particularly large language models, to historical discourse analysis within an interdisciplinary framework combining computer science, history, economics, and management. One thesis leveraged LLMs and digitized press archives from Gallica to study narratives about corporate profit from 1907 to 1950, employing methods such as sentiment analysis, multimodal content analysis, and diachronic network mapping. It also integrated corporate accounting data from Equipex DFIH and annual reports to link discourse with firm-level behavior. Another major activity was the organization of the NLDB 2026 conference, which gathered researchers to discuss topics like large language models, bias, and transparency, though this is not a research project itself. Overall, the year’s research landscape is defined by the use of historical datasets and computationally intensive NLP methods to address societal questions."
        },
        "yearReqs": {
            "2003": [
                {
                    "name": "Spanish political protest and economic integration data",
                    "group": "Data"
                },
                {
                    "name": "Text corpora for sentiment and document retrieval",
                    "group": "Data"
                },
                {
                    "name": "Graph-based algorithms for text processing",
                    "group": "Methods"
                },
                {
                    "name": "Statistical regression analysis",
                    "group": "Methods"
                }
            ],
            "2006": [
                {
                    "name": "Blogosphere data",
                    "group": "Data"
                },
                {
                    "name": "Coalition discovery algorithms",
                    "group": "Methods"
                },
                {
                    "name": "Large-scale data processing compute",
                    "group": "Compute"
                }
            ],
            "2007": [
                {
                    "name": "Archival and textual primary sources",
                    "group": "Data"
                },
                {
                    "name": "Internet and media text data",
                    "group": "Data"
                },
                {
                    "name": "Qualitative research methods",
                    "group": "Methods"
                },
                {
                    "name": "Statistical and computational analysis",
                    "group": "Methods"
                },
                {
                    "name": "Web scraping and NLP tools",
                    "group": "Tools"
                },
                {
                    "name": "Data processing computational resources",
                    "group": "Compute"
                }
            ],
            "2008": [
                {
                    "name": "Subjectivity and sentiment lexicons",
                    "group": "Data"
                },
                {
                    "name": "Financial market data",
                    "group": "Data"
                },
                {
                    "name": "Online media and community data",
                    "group": "Data"
                },
                {
                    "name": "Word sense disambiguation for subjectivity",
                    "group": "Methods"
                },
                {
                    "name": "Negation handling in opinion retrieval",
                    "group": "Methods"
                },
                {
                    "name": "Temporal sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Parallel algorithms for correlation and clustering",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning for community and sentiment mining",
                    "group": "Methods"
                },
                {
                    "name": "High-performance computing clusters",
                    "group": "Compute"
                }
            ],
            "2009": [
                {
                    "name": "Online text corpora (blogs, news, reviews)",
                    "group": "Data"
                },
                {
                    "name": "Subjectivity and sentiment lexicons",
                    "group": "Data"
                },
                {
                    "name": "Machine learning for sentiment classification",
                    "group": "Methods"
                },
                {
                    "name": "Statistical and symbolic NLP",
                    "group": "Methods"
                },
                {
                    "name": "Cloud computing infrastructure",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation of linguistic data",
                    "group": "Human"
                }
            ],
            "2010": [
                {
                    "name": "News and blog text corpora",
                    "group": "Data"
                },
                {
                    "name": "Survey and census demographic data",
                    "group": "Data"
                },
                {
                    "name": "Historical archival records",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis / opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Natural language and statistical analysis for trend detection",
                    "group": "Methods"
                },
                {
                    "name": "Cloud computing infrastructure",
                    "group": "Compute"
                },
                {
                    "name": "Corpus analysis software",
                    "group": "Tools"
                }
            ],
            "2011": [
                {
                    "name": "Sentiment analysis and opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Mixed methods research design",
                    "group": "Methods"
                },
                {
                    "name": "Online text and social media content",
                    "group": "Data"
                },
                {
                    "name": "Semantic role labeling and text analysis tools",
                    "group": "Tools"
                },
                {
                    "name": "Manual content coding and survey administration",
                    "group": "Human"
                },
                {
                    "name": "Statistical modeling and classification compute",
                    "group": "Compute"
                }
            ],
            "2012": [
                {
                    "name": "Social media text datasets",
                    "group": "Data"
                },
                {
                    "name": "Lexical resources (WordNet, FrameNet, PropBank, VerbNet)",
                    "group": "Data"
                },
                {
                    "name": "Large-scale annotated corpora for NLP",
                    "group": "Data"
                },
                {
                    "name": "Multilingual text resources for sentiment and named entity recognition",
                    "group": "Data"
                },
                {
                    "name": "Unsupervised or weakly-supervised machine learning for grammar and semantics",
                    "group": "Methods"
                },
                {
                    "name": "Sentiment analysis and opinion influence modeling",
                    "group": "Methods"
                },
                {
                    "name": "High-performance computing infrastructure for large-scale text processing",
                    "group": "Compute"
                },
                {
                    "name": "Expert annotation and gold standard creation for semantic roles and frames",
                    "group": "Human"
                },
                {
                    "name": "API-based data collection and visualization tools for social media",
                    "group": "Tools"
                }
            ],
            "2013": [
                {
                    "name": "Social media and web text data",
                    "group": "Data"
                },
                {
                    "name": "Google Trends and search data",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis and opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning and natural language processing",
                    "group": "Methods"
                },
                {
                    "name": "Multilingual text analysis platforms and lexical resources",
                    "group": "Tools"
                },
                {
                    "name": "Large-scale data processing infrastructure",
                    "group": "Compute"
                }
            ],
            "2014": [
                {
                    "name": "Social media text data",
                    "group": "Data"
                },
                {
                    "name": "Natural language processing (NLP) for sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning and statistical modeling tools",
                    "group": "Tools"
                },
                {
                    "name": "Distributed computing (Hadoop and MapReduce)",
                    "group": "Compute"
                },
                {
                    "name": "User-generated content from web platforms",
                    "group": "Data"
                },
                {
                    "name": "Automated text summarization and topic modeling",
                    "group": "Methods"
                }
            ],
            "2015": [
                {
                    "name": "News articles",
                    "group": "Data"
                },
                {
                    "name": "Social media data (Twitter, Facebook, StockTwits, blogs)",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis / opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Natural language processing (NLP)",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning / deep learning",
                    "group": "Methods"
                },
                {
                    "name": "Textual analysis / sentiment lexicon tools",
                    "group": "Tools"
                },
                {
                    "name": "Large-scale data processing infrastructure",
                    "group": "Compute"
                },
                {
                    "name": "Human annotation / evaluation (crowdsourcing, expert review)",
                    "group": "Human"
                }
            ],
            "2016": [
                {
                    "name": "Large-scale text corpora from social media and news",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis and opinion mining",
                    "group": "Methods"
                },
                {
                    "name": "Natural language processing (NLP) and text mining",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning and deep learning",
                    "group": "Methods"
                },
                {
                    "name": "Statistical and econometric modeling",
                    "group": "Methods"
                },
                {
                    "name": "Visualization and data presentation tools",
                    "group": "Tools"
                }
            ],
            "2017": [
                {
                    "name": "Social media text data (Twitter, Facebook, etc.)",
                    "group": "Data"
                },
                {
                    "name": "Financial news and reports",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Natural language processing (NLP)",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning (including deep learning)",
                    "group": "Methods"
                },
                {
                    "name": "Social network analysis (SNA)",
                    "group": "Methods"
                },
                {
                    "name": "Bayesian modeling",
                    "group": "Methods"
                },
                {
                    "name": "Agent-based modeling",
                    "group": "Methods"
                },
                {
                    "name": "Pre-trained language models (e.g., BERT)",
                    "group": "Tools"
                },
                {
                    "name": "GPU compute for model training",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation of text data",
                    "group": "Human"
                }
            ],
            "2018": [
                {
                    "name": "Social media text data",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic modeling (Latent Dirichlet Allocation)",
                    "group": "Methods"
                },
                {
                    "name": "Deep neural networks",
                    "group": "Methods"
                },
                {
                    "name": "Python NLP libraries",
                    "group": "Tools"
                },
                {
                    "name": "GPU compute for deep learning",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation for sentiment and topics",
                    "group": "Human"
                }
            ],
            "2019": [
                {
                    "name": "Sentiment and Emotion Analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic Modeling",
                    "group": "Methods"
                },
                {
                    "name": "Deep Learning (including LSTM, Transformers, CNNs)",
                    "group": "Methods"
                },
                {
                    "name": "Social Media Data (Twitter, Facebook, etc.)",
                    "group": "Data"
                },
                {
                    "name": "News Article Corpora",
                    "group": "Data"
                },
                {
                    "name": "Python and NLP Libraries (e.g., NLTK, spaCy, scikit-learn)",
                    "group": "Tools"
                },
                {
                    "name": "GPU Computing for Deep Learning",
                    "group": "Compute"
                },
                {
                    "name": "Expert Annotation for Text Classification",
                    "group": "Human"
                }
            ],
            "2020": [
                {
                    "name": "Social media data (Twitter, Facebook, Reddit)",
                    "group": "Data"
                },
                {
                    "name": "Textual corpora (archival descriptions, novels, legal cases, news)",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic modeling",
                    "group": "Methods"
                },
                {
                    "name": "Deep learning (neural networks, transformers)",
                    "group": "Methods"
                },
                {
                    "name": "Natural Language Processing (NLP) libraries and APIs",
                    "group": "Tools"
                },
                {
                    "name": "GPU compute for training deep learning models",
                    "group": "Compute"
                },
                {
                    "name": "Manual annotation and labeling of text data",
                    "group": "Human"
                }
            ],
            "2021": [
                {
                    "name": "Social media text data",
                    "group": "Data"
                },
                {
                    "name": "News article corpus",
                    "group": "Data"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Deep learning for NLP and computer vision",
                    "group": "Methods"
                },
                {
                    "name": "GPU compute for deep learning training",
                    "group": "Compute"
                },
                {
                    "name": "Qualitative interviews and surveys",
                    "group": "Human"
                }
            ],
            "2022": [
                {
                    "name": "Sentiment Analysis",
                    "group": "Methods"
                },
                {
                    "name": "Machine Learning / Deep Learning Models",
                    "group": "Methods"
                },
                {
                    "name": "Public and Proprietary Datasets",
                    "group": "Data"
                },
                {
                    "name": "GPU / High-Performance Computing",
                    "group": "Compute"
                },
                {
                    "name": "Human Annotation / Expert Validation",
                    "group": "Human"
                },
                {
                    "name": "NLP Libraries and Frameworks",
                    "group": "Tools"
                }
            ],
            "2023": [
                {
                    "name": "Social Media Text Data",
                    "group": "Data"
                },
                {
                    "name": "Natural Language Processing (NLP) Techniques",
                    "group": "Methods"
                },
                {
                    "name": "Machine Learning for Efficiency and Reduced Supervision",
                    "group": "Methods"
                },
                {
                    "name": "Large Language Models (LLMs)",
                    "group": "Data"
                },
                {
                    "name": "User-generated Content and Reviews",
                    "group": "Data"
                }
            ],
            "2024": [
                {
                    "name": "Sentiment analysis / emotion detection",
                    "group": "Methods"
                },
                {
                    "name": "Large Language Models (LLMs) / transformer-based NLP",
                    "group": "Methods"
                },
                {
                    "name": "Machine learning frameworks and libraries",
                    "group": "Tools"
                },
                {
                    "name": "Social media and online text data",
                    "group": "Data"
                },
                {
                    "name": "GPU compute for model training and inference",
                    "group": "Compute"
                },
                {
                    "name": "Text mining and NLP libraries (e.g., NLTK, spaCy, Gensim)",
                    "group": "Tools"
                },
                {
                    "name": "Qualitative methods (interviews, focus groups, discourse analysis)",
                    "group": "Methods"
                },
                {
                    "name": "Manual annotation / labeling of data",
                    "group": "Human"
                },
                {
                    "name": "Financial and economic datasets",
                    "group": "Data"
                },
                {
                    "name": "Statistical and econometric analysis",
                    "group": "Methods"
                }
            ],
            "2025": [
                {
                    "name": "Natural Language Processing (NLP) for sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "Large Language Models (LLMs) for text generation and analysis",
                    "group": "Methods"
                },
                {
                    "name": "Topic modeling",
                    "group": "Methods"
                },
                {
                    "name": "BERT-based models (e.g., FinBERT, EconBERT)",
                    "group": "Tools"
                },
                {
                    "name": "Social media data (Twitter, Facebook, Instagram, Tripadvisor)",
                    "group": "Data"
                },
                {
                    "name": "Mixed-methods (qualitative and quantitative)",
                    "group": "Methods"
                },
                {
                    "name": "Causal inference and quasi-experimental designs",
                    "group": "Methods"
                },
                {
                    "name": "GPU compute for training deep learning models",
                    "group": "Compute"
                },
                {
                    "name": "Machine learning for prediction and trend detection",
                    "group": "Methods"
                },
                {
                    "name": "Financial and economic datasets (e.g., hedge fund letters, proxy voting records, options data)",
                    "group": "Data"
                }
            ],
            "2026": [
                {
                    "name": "Digitized historical press archives",
                    "group": "Data"
                },
                {
                    "name": "Corporate accounting and annual report data",
                    "group": "Data"
                },
                {
                    "name": "Large Language Model tailored for historical discourse",
                    "group": "Methods"
                },
                {
                    "name": "Multimodal content analysis and diachronic network mapping",
                    "group": "Methods"
                },
                {
                    "name": "Sentiment analysis",
                    "group": "Methods"
                },
                {
                    "name": "User-friendly visualization tools",
                    "group": "Tools"
                }
            ]
        }
    }

};

export const FIELD_ORDER = ['sentiment_analysis','room_temperature_superconductor'];
